export {
  Heading,
  Text,
  Typography,
  headingClassNames,
  textClassNames,
  typographyClassNames,
  type HeadingLevel,
  type HeadingProps,
  type HeadingVisualLevel,
  type TextElement,
  type TextProps,
  type TextSize,
  type TypographyAlign,
  type TypographyElement,
  type TypographyLineClamp,
  type TypographyProps,
  type TypographySize,
  type TypographyTone,
  type TypographyVariant,
  type TypographyWeight,
} from "./typography";
