import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, within } from "storybook/test";
import {
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Container,
  DethinkProvider,
  Field,
  FieldContent,
  FieldControl,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldLegend,
  FieldSet,
  FieldTitle,
  Form,
  Grid,
  Stack,
  Text,
} from "@dethink/components";

const meta = {
  title: "Components/FormField",
  component: Field,
} satisfies Meta<typeof Field>;

export default meta;

type Story = StoryObj<typeof meta>;

const nativeInputClasses =
  "min-h-density-control w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground shadow-sm outline-none motion-safe:transition-[border-color,box-shadow] motion-safe:duration-150 placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/20 disabled:cursor-not-allowed disabled:opacity-60 aria-[invalid=true]:border-destructive aria-[invalid=true]:ring-2 aria-[invalid=true]:ring-destructive/15";

const nativeTextareaClasses =
  "min-h-28 w-full resize-y rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground shadow-sm outline-none motion-safe:transition-[border-color,box-shadow] motion-safe:duration-150 placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/20 disabled:cursor-not-allowed disabled:opacity-60 aria-[invalid=true]:border-destructive aria-[invalid=true]:ring-2 aria-[invalid=true]:ring-destructive/15";

export const BaseField: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Form>
          <Field id="workspace-name">
            <FieldLabel>Workspace name</FieldLabel>
            <FieldControl asChild>
              <input
                className={nativeInputClasses}
                name="workspaceName"
                placeholder="Acme Operations"
              />
            </FieldControl>
            <FieldDescription>
              This name appears in navigation and shared reports.
            </FieldDescription>
          </Field>
        </Form>
      </Container>
    </DethinkProvider>
  ),
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const label = canvas.getByText("Workspace name");
    const input = canvas.getByLabelText("Workspace name");

    await userEvent.click(label);

    await expect(input).toHaveFocus();
    await expect(input).toHaveAttribute("aria-describedby");
  },
};

export const RequiredAndInvalid: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Form>
          <Field id="billing-email" invalid required>
            <FieldLabel>Billing email</FieldLabel>
            <FieldControl asChild>
              <input
                className={nativeInputClasses}
                name="billingEmail"
                type="email"
                defaultValue="billing"
              />
            </FieldControl>
            <FieldDescription>Use a monitored finance team inbox.</FieldDescription>
            <FieldError id="billing-email-error">
              Enter a valid email address.
            </FieldError>
          </Field>
        </Form>
      </Container>
    </DethinkProvider>
  ),
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const input = canvas.getByLabelText(/Billing email/);

    await expect(input).toHaveAttribute("aria-invalid", "true");
    await expect(input).toHaveAttribute("aria-errormessage", "billing-email-error");
  },
};

export const DisabledAndReadOnly: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Form>
          <Field id="tenant-id" readOnly>
            <FieldLabel>Tenant ID</FieldLabel>
            <FieldControl asChild>
              <input className={nativeInputClasses} readOnly defaultValue="tenant_93a8" />
            </FieldControl>
            <FieldDescription>Generated by the platform.</FieldDescription>
          </Field>
          <Field id="owner-email" disabled>
            <FieldLabel>Owner email</FieldLabel>
            <FieldControl asChild>
              <input
                className={nativeInputClasses}
                disabled
                defaultValue="owner@example.com"
              />
            </FieldControl>
          </Field>
        </Form>
      </Container>
    </DethinkProvider>
  ),
};

export const HorizontalSettingsRows: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Form>
          {[
            {
              description: "Send weekly adoption and reliability summaries.",
              id: "weekly-summary",
              title: "Weekly summary",
            },
            {
              description: "Alert owners when error budgets are nearly spent.",
              id: "budget-alerts",
              title: "Budget alerts",
            },
          ].map((item) => (
            <Field key={item.id} id={item.id} orientation="horizontal">
              <FieldContent>
                <FieldLabel>{item.title}</FieldLabel>
                <FieldDescription>{item.description}</FieldDescription>
              </FieldContent>
              <FieldControl asChild>
                <input
                  className="mt-0.5 size-5 accent-primary"
                  name={item.id}
                  type="checkbox"
                />
              </FieldControl>
            </Field>
          ))}
        </Form>
      </Container>
    </DethinkProvider>
  ),
};

export const GroupedFieldSet: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Form>
          <FieldSet aria-describedby="notification-channels-help">
            <FieldLegend>Notification channels</FieldLegend>
            <FieldDescription id="notification-channels-help">
              Choose every channel that should receive alerts.
            </FieldDescription>
            <FieldGroup>
              {["Email", "Slack", "Webhook"].map((label) => (
                <Field key={label} id={`channel-${label.toLowerCase()}`} orientation="horizontal">
                  <FieldLabel>{label}</FieldLabel>
                  <FieldControl asChild>
                    <input
                      className="mt-0.5 size-5 accent-primary"
                      name="channels"
                      type="checkbox"
                      value={label.toLowerCase()}
                    />
                  </FieldControl>
                </Field>
              ))}
            </FieldGroup>
          </FieldSet>
        </Form>
      </Container>
    </DethinkProvider>
  ),
};

export const CardComposition: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="md">
        <Card as="section">
          <CardHeader>
            <CardTitle>Workspace settings</CardTitle>
            <CardDescription>
              Field primitives compose inside Card without taking over validation.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Form>
              <Grid columns="2" gap="4">
                <Field id="workspace-region">
                  <FieldLabel>Region</FieldLabel>
                  <FieldControl asChild>
                    <input className={nativeInputClasses} defaultValue="us-east-1" />
                  </FieldControl>
                </Field>
                <Field id="workspace-tier">
                  <FieldLabel>Tier</FieldLabel>
                  <FieldControl asChild>
                    <input className={nativeInputClasses} defaultValue="Business" />
                  </FieldControl>
                </Field>
              </Grid>
              <Field id="workspace-notes">
                <FieldLabel>Release notes</FieldLabel>
                <FieldControl asChild>
                  <textarea
                    className={nativeTextareaClasses}
                    defaultValue="Coordinate launch review before enabling production traffic."
                  />
                </FieldControl>
              </Field>
              <Button type="submit">Save changes</Button>
            </Form>
          </CardContent>
        </Card>
      </Container>
    </DethinkProvider>
  ),
};

export const ThemeDensityAndRTL: Story = {
  render: () => (
    <Grid columns="1" gap="4">
      <DethinkProvider theme="dark" density="compact" className="bg-background p-6">
        <Container size="sm">
          <Form>
            <Field id="compact-key" required>
              <FieldLabel>API key name</FieldLabel>
              <FieldControl asChild>
                <input className={nativeInputClasses} placeholder="Production key" />
              </FieldControl>
              <FieldDescription>Compact dark mode keeps helper copy readable.</FieldDescription>
            </Field>
          </Form>
        </Container>
      </DethinkProvider>
      <DethinkProvider theme="light" density="comfortable" dir="rtl" className="p-6">
        <Container size="sm">
          <Form>
            <Field id="rtl-owner" orientation="horizontal">
              <FieldContent>
                <FieldTitle>Owner review</FieldTitle>
                <Text size="sm" tone="muted">
                  Logical spacing keeps the checkbox aligned in RTL.
                </Text>
              </FieldContent>
              <FieldControl asChild>
                <input className="mt-0.5 size-5 accent-primary" type="checkbox" />
              </FieldControl>
            </Field>
          </Form>
        </Container>
      </DethinkProvider>
    </Grid>
  ),
};
