import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, within } from "storybook/test";
import {
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Container,
  DethinkProvider,
  Field,
  FieldControl,
  FieldDescription,
  FieldError,
  FieldLabel,
  Form,
  Input,
  Stack,
} from "@dethink/components";

const meta = {
  title: "Components/Input",
  component: Input,
  args: {
    placeholder: "Type a value",
  },
  argTypes: {
    controlSize: {
      control: "inline-radio",
      options: ["sm", "md", "lg"],
    },
    invalid: {
      control: "boolean",
    },
  },
} satisfies Meta<typeof Input>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Base: Story = {
  render: (args) => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Input {...args} aria-label="Base input" />
      </Container>
    </DethinkProvider>
  ),
};

export const FieldComposition: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Form>
          <Field id="workspace-slug" required>
            <FieldLabel>Workspace slug</FieldLabel>
            <FieldControl asChild>
              <Input
                autoComplete="organization"
                name="workspaceSlug"
                placeholder="acme-ops"
              />
            </FieldControl>
            <FieldDescription>
              Used in URLs, audit logs, and shared report exports.
            </FieldDescription>
          </Field>
        </Form>
      </Container>
    </DethinkProvider>
  ),
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const label = canvas.getByText("Workspace slug");
    const input = canvas.getByLabelText(/Workspace slug/);

    await userEvent.click(label);

    await expect(input).toHaveFocus();
    await expect(input).toHaveAttribute("aria-describedby");
  },
};

export const InvalidRequired: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Field id="billing-email" invalid required>
          <FieldLabel>Billing email</FieldLabel>
          <FieldControl asChild>
            <Input name="billingEmail" type="email" defaultValue="billing" />
          </FieldControl>
          <FieldDescription>Use a monitored finance team inbox.</FieldDescription>
          <FieldError>Enter a valid billing email address.</FieldError>
        </Field>
      </Container>
    </DethinkProvider>
  ),
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const input = canvas.getByLabelText(/Billing email/);

    await expect(input).toHaveAttribute("aria-invalid", "true");
    await expect(input).toHaveAttribute("aria-errormessage", "billing-email-error");
  },
};

export const DisabledAndReadOnly: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Stack gap="4">
          <Field id="tenant-id" readOnly>
            <FieldLabel>Tenant ID</FieldLabel>
            <FieldControl asChild>
              <Input readOnly defaultValue="tenant_93a8" />
            </FieldControl>
            <FieldDescription>Generated by the platform.</FieldDescription>
          </Field>
          <Field id="owner-email" disabled>
            <FieldLabel>Owner email</FieldLabel>
            <FieldControl asChild>
              <Input disabled defaultValue="owner@example.com" />
            </FieldControl>
          </Field>
        </Stack>
      </Container>
    </DethinkProvider>
  ),
};

export const AuthCard: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Card as="section">
          <CardHeader>
            <CardTitle>Sign in</CardTitle>
            <CardDescription>
              Native form controls keep browser autofill and password managers intact.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Form action="/login" method="post">
              <Field id="auth-email" required>
                <FieldLabel>Email</FieldLabel>
                <FieldControl asChild>
                  <Input
                    autoComplete="username"
                    name="email"
                    placeholder="you@example.com"
                    type="email"
                  />
                </FieldControl>
              </Field>
              <Field id="auth-password" required>
                <FieldLabel>Password</FieldLabel>
                <FieldControl asChild>
                  <Input
                    autoComplete="current-password"
                    name="password"
                    type="password"
                  />
                </FieldControl>
              </Field>
              <Button type="submit">Continue</Button>
            </Form>
          </CardContent>
        </Card>
      </Container>
    </DethinkProvider>
  ),
};

export const ThemeDensityAndRTL: Story = {
  render: () => (
    <div className="grid gap-4">
      {(["light", "dark"] as const).map((theme) => (
        <DethinkProvider
          key={theme}
          density={theme === "light" ? "compact" : "comfortable"}
          dir={theme === "dark" ? "rtl" : "ltr"}
          theme={theme}
          className="rounded-lg border border-border p-6"
        >
          <Container size="sm">
            <Field id={`input-${theme}`}>
              <FieldLabel>{theme === "dark" ? "שם סביבת עבודה" : "Workspace"}</FieldLabel>
              <FieldControl asChild>
                <Input
                  defaultValue={theme === "dark" ? "פעולות" : "Operations"}
                  name={`workspace-${theme}`}
                />
              </FieldControl>
              <FieldDescription>
                {theme === "dark"
                  ? "RTL, density, and dark mode share the same control contract."
                  : "Compact density keeps the native input scannable."}
              </FieldDescription>
            </Field>
          </Container>
        </DethinkProvider>
      ))}
    </div>
  ),
};
