import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, within } from "storybook/test";
import {
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Container,
  DethinkProvider,
  Field,
  FieldControl,
  FieldDescription,
  FieldError,
  FieldLabel,
  Form,
  Stack,
  Textarea,
} from "@dethink/components";

const meta = {
  title: "Components/Textarea",
  component: Textarea,
  args: {
    placeholder: "Write a note",
  },
  argTypes: {
    controlSize: {
      control: "inline-radio",
      options: ["sm", "md", "lg"],
    },
    resize: {
      control: "inline-radio",
      options: ["none", "vertical", "horizontal", "both"],
    },
    invalid: {
      control: "boolean",
    },
  },
} satisfies Meta<typeof Textarea>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Base: Story = {
  render: (args) => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Textarea {...args} aria-label="Base textarea" rows={4} />
      </Container>
    </DethinkProvider>
  ),
};

export const FieldComposition: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Form>
          <Field id="release-note" required>
            <FieldLabel>Release note</FieldLabel>
            <FieldControl asChild>
              <Textarea
                name="releaseNote"
                placeholder="Summarize the user-visible change"
                rows={5}
              />
            </FieldControl>
            <FieldDescription>
              This appears in release emails and audit history.
            </FieldDescription>
          </Field>
        </Form>
      </Container>
    </DethinkProvider>
  ),
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const label = canvas.getByText("Release note");
    const textarea = canvas.getByLabelText(/Release note/);

    await userEvent.click(label);

    await expect(textarea).toHaveFocus();
    await expect(textarea).toHaveAttribute("aria-describedby");
  },
};

export const InvalidRequired: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Field id="approval-note" invalid required>
          <FieldLabel>Approval note</FieldLabel>
          <FieldControl asChild>
            <Textarea name="approvalNote" defaultValue="No" rows={4} />
          </FieldControl>
          <FieldDescription>Explain the approval decision.</FieldDescription>
          <FieldError>Add enough context for an auditor.</FieldError>
        </Field>
      </Container>
    </DethinkProvider>
  ),
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const textarea = canvas.getByLabelText(/Approval note/);

    await expect(textarea).toHaveAttribute("aria-invalid", "true");
    await expect(textarea).toHaveAttribute("aria-errormessage", "approval-note-error");
  },
};

export const ResizeOptions: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="md">
        <div className="grid gap-4 md:grid-cols-2">
          {(["vertical", "none", "horizontal", "both"] as const).map((resize) => (
            <Field key={resize} id={`textarea-${resize}`}>
              <FieldLabel className="capitalize">{resize}</FieldLabel>
              <FieldControl asChild>
                <Textarea
                  defaultValue="Resize behavior is explicit."
                  resize={resize}
                  rows={3}
                />
              </FieldControl>
            </Field>
          ))}
        </div>
      </Container>
    </DethinkProvider>
  ),
};

export const DisabledAndReadOnly: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Stack gap="4">
          <Field id="generated-summary" readOnly>
            <FieldLabel>Generated summary</FieldLabel>
            <FieldControl asChild>
              <Textarea readOnly defaultValue="Review generated by the platform." />
            </FieldControl>
          </Field>
          <Field id="locked-note" disabled>
            <FieldLabel>Locked note</FieldLabel>
            <FieldControl asChild>
              <Textarea disabled defaultValue="Locked after approval." />
            </FieldControl>
          </Field>
        </Stack>
      </Container>
    </DethinkProvider>
  ),
};

export const SettingsCard: Story = {
  render: () => (
    <DethinkProvider theme="light" className="p-6">
      <Container size="sm">
        <Card as="section">
          <CardHeader>
            <CardTitle>Incident template</CardTitle>
            <CardDescription>
              Multiline fields keep native form behavior and browser editing tools.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Form action="/incident-template" method="post">
              <Field id="incident-template">
                <FieldLabel>Template</FieldLabel>
                <FieldControl asChild>
                  <Textarea
                    name="template"
                    defaultValue={"Impact:\nOwner:\nNext update:"}
                    rows={6}
                  />
                </FieldControl>
                <FieldDescription>Used when opening a new incident report.</FieldDescription>
              </Field>
              <Button type="submit">Save template</Button>
            </Form>
          </CardContent>
        </Card>
      </Container>
    </DethinkProvider>
  ),
};

export const ThemeDensityAndRTL: Story = {
  render: () => (
    <div className="grid gap-4">
      {(["light", "dark"] as const).map((theme) => (
        <DethinkProvider
          key={theme}
          density={theme === "light" ? "compact" : "comfortable"}
          dir={theme === "dark" ? "rtl" : "ltr"}
          theme={theme}
          className="rounded-lg border border-border p-6"
        >
          <Container size="sm">
            <Field id={`textarea-${theme}`}>
              <FieldLabel>{theme === "dark" ? "הערות" : "Notes"}</FieldLabel>
              <FieldControl asChild>
                <Textarea
                  defaultValue={
                    theme === "dark"
                      ? "שדה טקסט מרובה שורות"
                      : "Compact density keeps editing surfaces scannable."
                  }
                  rows={4}
                />
              </FieldControl>
              <FieldDescription>
                {theme === "dark"
                  ? "RTL, density, and dark mode share the same textarea contract."
                  : "Textarea follows the same FormField wiring."}
              </FieldDescription>
            </Field>
          </Container>
        </DethinkProvider>
      ))}
    </div>
  ),
};
